server:
  port: 8012

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:}
    username: ${DATABSE_USER:postgres}
    password: ${DATABASE_PASSWORD:}


  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: ${REDIS_HOST:}
    password: ${REDIS_PASSWORD}
    port: 6379

user:
  profile: ${USER_PROFILE:}
  hax: ${USER_BACKGROUND:000000}


auth:
  jwt:
    secret: ${JWT_SECRET_KEY:}
    header: BEAREA
