server:
  port: 8012

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/me
    username: postgres
    password: ${PASSWORD:}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

user:
  profile: ${P_BASIC:}
  hax: ${H_BASIC:}